import turtle
import math
import random

t = turtle.Turtle()
t.hideturtle
turtle.colormode(255)
#background big
t.pensize(10)
t.penup()
t.goto(0,-390)
t.pendown()
t.color("cyan", "aquamarine")
t.begin_fill()
t.circle(400)
t.end_fill()

x = random.randrange(8,20)
for i in range(5,x):
   rp = random.randrange(0,101)
   gp = random.randrange(200,255)
   bp = random.randrange(170,255)
   rf = random.randrange(0,101)
   gf = random.randrange(200,255)
   bf = random.randrange(170,255)
   xloc = random.randrange(-800,800)
   yloc = random.randrange(-400,400)
   t.pensize(random.randrange(0,11))
   t.penup()
   t.goto(xloc,yloc)
   t.pendown()
   t.pencolor(rp,gp,bp)
   t.fillcolor(rf,gf,bf)
   t.begin_fill()
   t.circle(random.randrange(10,100))
   t.end_fill()

#head
t.penup()
t.goto(0, 150)
t.pendown()
t.color("forest green","lime green")
t.begin_fill()
t.shape("circle")
t.shapesize(6,10,7)
head = t.stamp()

#tail and legs
t.penup()
t.shapesize(3,8,6)
t.goto(0,-120)
t.tilt(90)
tail = t.stamp()

t.goto(100,50)
t.tilt(90)
t.tilt(45)
leg1 = t.stamp()

t.goto(-100,50)
t.tilt(90)
leg2 = t.stamp()

t.goto(-100,-70)
t.tilt(90)
leg3 = t.stamp()

t.goto(100,-70)
t.tilt(90)
leg4 = t.stamp()

#shell
t.color("dark green","sea green")
t.shapesize(15,15,10)
t.goto(0,0)
body = t.stamp()
t.end_fill()
t.hideturtle()
t.pensize(9)
t.penup()
t.setheading(90)
t.goto(0,150)
t.pendown()
t.setheading(215)
Size=150
Size = (Size*(math.sqrt(3)/2)) / math.sin(math.radians(65))
for i in range(0,30):  
   t.forward(Size)
   t.left(60)
   Size = (Size*(math.sqrt(3)/2)) / math.sin(math.radians(70))
t.penup()
t.goto(0,-141)
t.setheading(0)
t.pendown()
t.pensize(10)
t.pencolor("forest green")
t.circle(140)

#eyes
t.penup()
t.pensize(4)
t.goto(55,155)
t.pendown()
t.color("black", "brown")
t.begin_fill()
t.circle(10)
t.penup()
t.goto(-55,155)
t.pendown()
t.circle(10)
t.end_fill()

t.penup()
t.pensize(1)
t.goto(60,160)
t.pendown()
t.color("white", "white")
t.begin_fill()
t.circle(2)
t.penup()
t.goto(-50,160)
t.pendown()
t.circle(2)
t.end_fill()
